### ISSUE TITLE
Factor analysis differs when grouping assets by sector 

### ISSUE THREAD

**Issue by ernestoeperez88** [quantopian/alphalens#153] opened 2017-05-10 17:24 UTC
Analyzing a factor with assets grouped by sector yields different results than analyzing without grouping. 

The following code reproduces the issue:
```
import alphalens
from quantopian.pipeline import Pipeline
from quantopian.research import run_pipeline
from quantopian.pipeline.filters.morningstar import Q1500US
from quantopian.pipeline.classifiers.morningstar import Sector
from quantopian.pipeline.data.morningstar import operation_ratios

MORNINGSTAR_SECTOR_CODES = {
     -1: 'Misc',
    101: 'Basic Materials',
    102: 'Consumer Cyclical',
    103: 'Financial Services',
    104: 'Real Estate',
    205: 'Consumer Defensive',
    206: 'Healthcare',
    207: 'Utilities',
    308: 'Communication Services',
    309: 'Energy',
    310: 'Industrials',
    311: 'Technology' ,    
}

def make_pipeline():
    factor_1 = operation_ratios.operation_margin.latest
    
    universe = (Q1500US() 
                & factor_1.notnull())
    
    pipe = Pipeline(
        columns={
            'factor': factor_1.rank(mask=universe, method='average'),
            'Sector': Sector(mask=universe),
        },
        screen=universe
    )
    return pipe

result = run_pipeline(make_pipeline(), start_date='2013-12-01', end_date='2014-12-01')
result.head()

assets = result.index.levels[1].unique()
pricing = get_pricing(assets, start_date='2013-12-01', end_date='2015-01-01', fields='open_price')

alphalens.tears.create_factor_tear_sheet(factor=result['factor'],
                                         prices=pricing,
                                         quantiles=2,
                                         periods=(1,5,10,30))

factor_data = alphalens.utils.get_clean_factor_and_forward_returns(result['factor'],
                                                                   pricing,
                                                                   groupby=result["Sector"],
                                                                   quantiles=2,
                                                                   periods=(1,5,10,30),
                                                                   groupby_labels=MORNINGSTAR_SECTOR_CODES
                                                                   )

alphalens.tears.create_full_tear_sheet(factor_data, 
                                       group_adjust=True, 
                                       by_group=True)
```

**Comment by ernestoeperez88** [comment] 2017-05-10 17:28
This file contain the output generated by the code.

[Factor Research.pdf](https://github.com/quantopian/alphalens/files/990697/Factor.Research.pdf)

**Comment by luca-s** [comment] 2017-05-10 19:03
The difference is due to` group_adjust=True` in the second plot. Please try without and let me know if the still differ.

**Comment by luca-s** [comment] 2017-05-11 18:21
I am closing this issue as this is the expected behaviour of `group_adjust` option. Feel free to reopen the issue if you discover something new

**Closed by luca-s** 2017-05-11 18:21 UTC
